// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';


var Vec2 = 0;

var Vec3 = 0;

var Vec4 = 0;

var Quat = 0;

var Quat2 = 0;

var Mat2 = 0;

var Mat2d = 0;

var Mat3 = 0;

var Mat4 = 0;

exports.Vec2 = Vec2;
exports.Vec3 = Vec3;
exports.Vec4 = Vec4;
exports.Quat = Quat;
exports.Quat2 = Quat2;
exports.Mat2 = Mat2;
exports.Mat2d = Mat2d;
exports.Mat3 = Mat3;
exports.Mat4 = Mat4;
/* No side effect */
